#############################################################################
# Makefile for building: bin_unix/rastersim
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mo. Jul 4 12:37:36 2016
# Project:  rastersim.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile rastersim.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -I. -Itmp_unix
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtSvg -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = tmp_unix/

####### Files

SOURCES       = src/main.cpp \
		src/data.cpp \
		src/robot.cpp \
		src/abstractplanner.cpp \
		src/astarplanner.cpp \
		src/dstarplanner.cpp \
		src/fdstarplanner.cpp \
		src/dstarliteplanner.cpp \
		src/zoomablewidget.cpp \
		src/visualizationwidget.cpp \
		src/flowlayout.cpp \
		src/simwidget.cpp \
		src/simmainwindow.cpp \
		src/rlcpens.cpp tmp_unix/moc_abstractplanner.cpp \
		tmp_unix/moc_dstarplanner.cpp \
		tmp_unix/moc_fdstarplanner.cpp \
		tmp_unix/moc_dstarliteplanner.cpp \
		tmp_unix/moc_simmainwindow.cpp \
		tmp_unix/moc_zoomablewidget.cpp \
		tmp_unix/moc_visualizationwidget.cpp \
		tmp_unix/qrc_rastersim.cpp
OBJECTS       = tmp_unix/main.o \
		tmp_unix/data.o \
		tmp_unix/robot.o \
		tmp_unix/abstractplanner.o \
		tmp_unix/astarplanner.o \
		tmp_unix/dstarplanner.o \
		tmp_unix/fdstarplanner.o \
		tmp_unix/dstarliteplanner.o \
		tmp_unix/zoomablewidget.o \
		tmp_unix/visualizationwidget.o \
		tmp_unix/flowlayout.o \
		tmp_unix/simwidget.o \
		tmp_unix/simmainwindow.o \
		tmp_unix/rlcpens.o \
		tmp_unix/moc_abstractplanner.o \
		tmp_unix/moc_dstarplanner.o \
		tmp_unix/moc_fdstarplanner.o \
		tmp_unix/moc_dstarliteplanner.o \
		tmp_unix/moc_simmainwindow.o \
		tmp_unix/moc_zoomablewidget.o \
		tmp_unix/moc_visualizationwidget.o \
		tmp_unix/qrc_rastersim.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		rastersim.pro
QMAKE_TARGET  = rastersim
DESTDIR       = bin_unix/
TARGET        = bin_unix/rastersim

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin_unix/ || $(MKDIR) bin_unix/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: rastersim.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSvg.prl \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile rastersim.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSvg.prl:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile rastersim.pro

dist: 
	@$(CHK_DIR_EXISTS) tmp_unix/rastersim1.0.0 || $(MKDIR) tmp_unix/rastersim1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) tmp_unix/rastersim1.0.0/ && $(COPY_FILE) --parents src/data.h src/robot.h src/abstractplanner.h src/astarplanner.h src/dstarplanner.h src/fdstarplanner.h src/dstarliteplanner.h src/simmainwindow.h src/simwidget.h src/zoomablewidget.h src/visualizationwidget.h src/flowlayout.h src/rlcpens.h tmp_unix/rastersim1.0.0/ && $(COPY_FILE) --parents rastersim.qrc tmp_unix/rastersim1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/data.cpp src/robot.cpp src/abstractplanner.cpp src/astarplanner.cpp src/dstarplanner.cpp src/fdstarplanner.cpp src/dstarliteplanner.cpp src/zoomablewidget.cpp src/visualizationwidget.cpp src/flowlayout.cpp src/simwidget.cpp src/simmainwindow.cpp src/rlcpens.cpp tmp_unix/rastersim1.0.0/ && (cd `dirname tmp_unix/rastersim1.0.0` && $(TAR) rastersim1.0.0.tar rastersim1.0.0 && $(COMPRESS) rastersim1.0.0.tar) && $(MOVE) `dirname tmp_unix/rastersim1.0.0`/rastersim1.0.0.tar.gz . && $(DEL_FILE) -r tmp_unix/rastersim1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: tmp_unix/moc_abstractplanner.cpp tmp_unix/moc_dstarplanner.cpp tmp_unix/moc_fdstarplanner.cpp tmp_unix/moc_dstarliteplanner.cpp tmp_unix/moc_simmainwindow.cpp tmp_unix/moc_zoomablewidget.cpp tmp_unix/moc_visualizationwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) tmp_unix/moc_abstractplanner.cpp tmp_unix/moc_dstarplanner.cpp tmp_unix/moc_fdstarplanner.cpp tmp_unix/moc_dstarliteplanner.cpp tmp_unix/moc_simmainwindow.cpp tmp_unix/moc_zoomablewidget.cpp tmp_unix/moc_visualizationwidget.cpp
tmp_unix/moc_abstractplanner.cpp: src/data.h \
		src/abstractplanner.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/abstractplanner.h -o tmp_unix/moc_abstractplanner.cpp

tmp_unix/moc_dstarplanner.cpp: src/abstractplanner.h \
		src/data.h \
		src/dstarplanner.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/dstarplanner.h -o tmp_unix/moc_dstarplanner.cpp

tmp_unix/moc_fdstarplanner.cpp: src/abstractplanner.h \
		src/data.h \
		src/fdstarplanner.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/fdstarplanner.h -o tmp_unix/moc_fdstarplanner.cpp

tmp_unix/moc_dstarliteplanner.cpp: src/abstractplanner.h \
		src/data.h \
		src/dstarliteplanner.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/dstarliteplanner.h -o tmp_unix/moc_dstarliteplanner.cpp

tmp_unix/moc_simmainwindow.cpp: src/simmainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/simmainwindow.h -o tmp_unix/moc_simmainwindow.cpp

tmp_unix/moc_zoomablewidget.cpp: src/zoomablewidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/zoomablewidget.h -o tmp_unix/moc_zoomablewidget.cpp

tmp_unix/moc_visualizationwidget.cpp: src/zoomablewidget.h \
		src/abstractplanner.h \
		src/data.h \
		src/visualizationwidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/visualizationwidget.h -o tmp_unix/moc_visualizationwidget.cpp

compiler_rcc_make_all: tmp_unix/qrc_rastersim.cpp
compiler_rcc_clean:
	-$(DEL_FILE) tmp_unix/qrc_rastersim.cpp
tmp_unix/qrc_rastersim.cpp: rastersim.qrc \
		res/rotate_90.svg \
		res/pen_cursor_mask.bmp \
		res/zoom_in.svg \
		res/tool_pen.svg \
		res/pen_cursor.bmp \
		res/tool_line.svg \
		res/rotate_270.svg \
		res/rotate_180.svg \
		res/mirror_vertical.svg \
		res/zoom_out.svg \
		res/noimage.svg \
		res/color_white.svg \
		res/tool_pointer.svg \
		res/tool_rect.svg \
		res/mirror_horizontal.svg \
		res/zoom_original.svg \
		res/color_black.svg
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name rastersim rastersim.qrc -o tmp_unix/qrc_rastersim.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

tmp_unix/main.o: src/main.cpp src/simmainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/main.o src/main.cpp

tmp_unix/data.o: src/data.cpp src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/data.o src/data.cpp

tmp_unix/robot.o: src/robot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/robot.o src/robot.cpp

tmp_unix/abstractplanner.o: src/abstractplanner.cpp src/abstractplanner.h \
		src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/abstractplanner.o src/abstractplanner.cpp

tmp_unix/astarplanner.o: src/astarplanner.cpp src/astarplanner.h \
		src/abstractplanner.h \
		src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/astarplanner.o src/astarplanner.cpp

tmp_unix/dstarplanner.o: src/dstarplanner.cpp src/dstarplanner.h \
		src/abstractplanner.h \
		src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/dstarplanner.o src/dstarplanner.cpp

tmp_unix/fdstarplanner.o: src/fdstarplanner.cpp src/fdstarplanner.h \
		src/abstractplanner.h \
		src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/fdstarplanner.o src/fdstarplanner.cpp

tmp_unix/dstarliteplanner.o: src/dstarliteplanner.cpp src/dstarliteplanner.h \
		src/abstractplanner.h \
		src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/dstarliteplanner.o src/dstarliteplanner.cpp

tmp_unix/zoomablewidget.o: src/zoomablewidget.cpp src/zoomablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/zoomablewidget.o src/zoomablewidget.cpp

tmp_unix/visualizationwidget.o: src/visualizationwidget.cpp src/visualizationwidget.h \
		src/zoomablewidget.h \
		src/abstractplanner.h \
		src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/visualizationwidget.o src/visualizationwidget.cpp

tmp_unix/flowlayout.o: src/flowlayout.cpp src/flowlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/flowlayout.o src/flowlayout.cpp

tmp_unix/simwidget.o: src/simwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/simwidget.o src/simwidget.cpp

tmp_unix/simmainwindow.o: src/simmainwindow.cpp src/simmainwindow.h \
		src/visualizationwidget.h \
		src/zoomablewidget.h \
		src/abstractplanner.h \
		src/data.h \
		src/astarplanner.h \
		src/dstarplanner.h \
		src/fdstarplanner.h \
		src/dstarliteplanner.h \
		src/flowlayout.h \
		src/rlcpens.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/simmainwindow.o src/simmainwindow.cpp

tmp_unix/rlcpens.o: src/rlcpens.cpp src/rlcpens.h \
		src/visualizationwidget.h \
		src/zoomablewidget.h \
		src/abstractplanner.h \
		src/data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/rlcpens.o src/rlcpens.cpp

tmp_unix/moc_abstractplanner.o: tmp_unix/moc_abstractplanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/moc_abstractplanner.o tmp_unix/moc_abstractplanner.cpp

tmp_unix/moc_dstarplanner.o: tmp_unix/moc_dstarplanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/moc_dstarplanner.o tmp_unix/moc_dstarplanner.cpp

tmp_unix/moc_fdstarplanner.o: tmp_unix/moc_fdstarplanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/moc_fdstarplanner.o tmp_unix/moc_fdstarplanner.cpp

tmp_unix/moc_dstarliteplanner.o: tmp_unix/moc_dstarliteplanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/moc_dstarliteplanner.o tmp_unix/moc_dstarliteplanner.cpp

tmp_unix/moc_simmainwindow.o: tmp_unix/moc_simmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/moc_simmainwindow.o tmp_unix/moc_simmainwindow.cpp

tmp_unix/moc_zoomablewidget.o: tmp_unix/moc_zoomablewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/moc_zoomablewidget.o tmp_unix/moc_zoomablewidget.cpp

tmp_unix/moc_visualizationwidget.o: tmp_unix/moc_visualizationwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/moc_visualizationwidget.o tmp_unix/moc_visualizationwidget.cpp

tmp_unix/qrc_rastersim.o: tmp_unix/qrc_rastersim.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp_unix/qrc_rastersim.o tmp_unix/qrc_rastersim.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

